#!/usr/bin/env python3
"""
derive_theme.py — turn a host application's palette into report theme tokens.

The report needs more colours than an app usually defines: six mutually
distinguishable categorical colours for Gantt bars and legends, a full dark
set, and a text colour for each series colour chosen by contrast. This script
derives all of that from a small number of seeds taken from the app.

Usage
  python3 derive_theme.py --primary "#2a78d6" > .reports/theme.css

  python3 derive_theme.py \
      --primary "#7c3aed" --plane "#faf9fb" --surface "#ffffff" \
      --ink "#18181b" --warn "#dc2626" --good "#16a34a" \
      --series "#7c3aed,#f97316,#0ea5e9" \
      > .reports/theme.css

  python3 derive_theme.py --primary "#c9a8ec" --mode dark \
      --plane "#161c17" --surface "#1e251f" --display-font serif \
      > .reports/theme.css

Only --primary is required. Anything not supplied is derived or falls back to
the default report palette. Pass --series to pin specific categorical colours
taken from the app (chart colours, status colours); remaining slots are
generated by rotating hue away from the last pinned colour.

--display-font / --body-font / --mono-font take a preset name (system, grotesk,
serif, slab, mono) or a literal CSS font-family list. Web fonts are never
emitted; pick the preset nearest the application's own faces.

--mode dark (or light) emits a single-scheme theme, for an application that
only has one. Leave the theme-toggle button out of the body in that case.

--check prints a contrast report to stderr instead of writing CSS.
"""

import argparse
import colorsys
import sys

DEFAULTS = {
    "plane": "#f7f8fa", "surface": "#ffffff", "surface_2": "#eef0f3",
    "ink": "#14171c", "warn": "#b42d2d", "good": "#2b7a4b",
}
DARK_DEFAULTS = {
    "plane": "#121417", "surface": "#1a1d22", "ink": "#eceef2",
}
DARK_INK = "#1a1a19"

# Named font stacks. Web fonts are not an option — the report has to render
# from disk in two years with no network — so each preset is the closest
# widely-installed stack to a family the application might be using.
FONTS = {
    "system":  'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Inter, Helvetica, Arial, sans-serif',
    "grotesk": '"Helvetica Neue", Helvetica, Arial, ui-sans-serif, system-ui, sans-serif',
    "serif":   '"Iowan Old Style", "Palatino Linotype", Palatino, Georgia, "Times New Roman", serif',
    "slab":    'Rockwell, "Roboto Slab", Georgia, "Times New Roman", serif',
    "mono":    'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
}


def font_stack(value, fallback):
    """A preset name, or a literal CSS font-family list passed straight through."""
    if not value:
        return FONTS[fallback]
    return FONTS.get(value.strip().lower(), value.strip())
LIGHT_INK = "#ffffff"


# ---------------------------------------------------------------- colour utils
def hex2rgb(h):
    h = h.strip().lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    if len(h) != 6:
        raise ValueError("not a hex colour: " + h)
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))


def rgb2hex(rgb):
    return "#" + "".join("%02x" % max(0, min(255, round(c * 255))) for c in rgb)


def hls(h):
    r, g, b = hex2rgb(h)
    return colorsys.rgb_to_hls(r, g, b)


def from_hls(h, l, s):
    return rgb2hex(colorsys.hls_to_rgb(h % 1.0, max(0.0, min(1.0, l)), max(0.0, min(1.0, s))))


def luminance(h):
    def ch(c):
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (ch(c) for c in hex2rgb(h))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a, b):
    la, lb = luminance(a), luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def best_ink(bg):
    """Text colour for a filled bar. Returns (hex, contrast_ratio)."""
    cw, cd = contrast(bg, LIGHT_INK), contrast(bg, DARK_INK)
    return (LIGHT_INK, cw) if cw >= cd else (DARK_INK, cd)


# ---------------------------------------------------------------- derivations
def tune(colour, plane=DEFAULTS["plane"]):
    """Pull a colour out of the mid-lightness band where neither white nor dark
    text reaches 4.5:1, and dark enough to read as a shape against the page.
    Keeps the hue. Two constraints: bar text >= 4.5:1, bar vs plane >= 2.2:1."""
    h, l, s = hls(colour)
    s = max(0.40, min(0.64, s))
    order = []
    start = max(0.28, min(0.52, l))
    for d in [i * 0.025 for i in range(0, 12)]:
        order.append(start - d)
        order.append(start + d)
    best, best_ratio = None, 0.0
    for cand_l in order:
        if not (0.20 <= cand_l <= 0.62):
            continue
        c = from_hls(h, cand_l, s)
        _ink, ratio = best_ink(c)
        if ratio >= 4.5 and contrast(c, plane) >= 2.2:
            return c
        if ratio > best_ratio:
            best, best_ratio = c, ratio
    return best or colour


def series(primary, pinned, n=6, plane=DEFAULTS["plane"]):
    """Six categorical colours. Pinned colours are tuned but keep their hue;
    remaining slots come from an evenly spaced hue wheel anchored on the first
    pinned colour, skipping any hue too close to one already taken."""
    pinned = list(pinned) if pinned else [primary]
    out = [tune(c, plane) for c in pinned[:n]]
    base_h = hls(out[0])[0]
    _, base_l, base_s = hls(out[0])

    grid = [(base_h + i / n) % 1.0 for i in range(n)]
    for gh in grid:
        if len(out) >= n:
            break
        cand = tune(from_hls(gh, base_l, base_s), plane)
        if all(hue_gap(cand, e) > 0.10 for e in out):
            out.append(cand)

    # if pinned colours clustered and the grid could not fill six slots,
    # fall back to a finer wheel
    k = 1
    while len(out) < n and k < 120:
        cand = tune(from_hls(base_h + k / 24.0, base_l, base_s), plane)
        if all(hue_gap(cand, e) > 0.07 for e in out):
            out.append(cand)
        k += 1
    return out[:n]


def hue_gap(a, b):
    ha, _, _ = hls(a)
    hb, _, _ = hls(b)
    d = abs(ha - hb) % 1.0
    return min(d, 1 - d)


def darken(h, amount=0.10):
    hh, l, s = hls(h)
    return from_hls(hh, l - amount, s)


def lighten(h, amount=0.10):
    hh, l, s = hls(h)
    return from_hls(hh, l + amount, s)


def mix(a, b, t):
    ra, rb = hex2rgb(a), hex2rgb(b)
    return rgb2hex(tuple(ra[i] * (1 - t) + rb[i] * t for i in range(3)))


def tint(colour, alpha):
    r, g, b = (round(c * 255) for c in hex2rgb(colour))
    return "rgba(%d,%d,%d,%.2f)" % (r, g, b, alpha)


# ---------------------------------------------------------------- emit
def build(args):
    primary = args.primary
    plane = args.plane or DEFAULTS["plane"]
    surface = args.surface or DEFAULTS["surface"]
    ink = args.ink or DEFAULTS["ink"]
    warn = args.warn or DEFAULTS["warn"]
    good = args.good or DEFAULTS["good"]
    surface_2 = args.surface_2 or mix(surface, ink, 0.06)

    pinned = [c.strip() for c in args.series.split(",")] if args.series else [primary]
    cs = series(primary, pinned, plane=plane)
    inks = [best_ink(c) for c in cs]

    # dark mode: same hues, lifted lightness so they hold up on a dark plane
    d_plane = args.dark_plane or DARK_DEFAULTS["plane"]
    d_surface = args.dark_surface or DARK_DEFAULTS["surface"]
    d_ink = DARK_DEFAULTS["ink"]
    d_surface_2 = mix(d_surface, d_ink, 0.05)
    d_cs = []
    for c in cs:
        h, l, s = hls(c)
        d_cs.append(from_hls(h, min(0.62, max(0.40, l + 0.04)), max(0.35, s - 0.05)))
    d_inks = [best_ink(c) for c in d_cs]
    d_warn = lighten(warn, 0.14)
    d_good = lighten(good, 0.16)

    flag = cs[3] if len(cs) > 3 else primary
    info = cs[0]

    def series_block(colours, ink_pairs, indent="  "):
        out = []
        for i, c in enumerate(colours):
            out.append("%s--c%d: %s;" % (indent, i, c))
        out.append("")
        for i, (col, _ratio) in enumerate(ink_pairs):
            out.append("%s--c%d-ink: %s;" % (indent, i, col))
        return "\n".join(out)

    light_semantic = "\n".join([
        "  --warn:      %s;" % warn,
        "  --good:      %s;" % good,
        "  --flag:      %s;" % flag,
        "  --info:      %s;" % info,
        "  --tint-warn: %s;" % tint(warn, 0.08),
        "  --tint-good: %s;" % tint(good, 0.09),
        "  --tint-flag: %s;" % tint(flag, 0.11),
        "  --tint-info: %s;" % tint(info, 0.08),
    ])
    dark_semantic = "\n".join([
        "    --warn:      %s;" % d_warn,
        "    --good:      %s;" % d_good,
        "    --flag:      %s;" % lighten(flag, 0.04),
        "    --info:      %s;" % lighten(info, 0.06),
        "    --tint-warn: %s;" % tint(d_warn, 0.13),
        "    --tint-good: %s;" % tint(d_good, 0.13),
        "    --tint-flag: %s;" % tint(flag, 0.15),
        "    --tint-info: %s;" % tint(info, 0.13),
    ])

    light_core = "\n".join([
        "  --plane:         %s;" % plane,
        "  --surface:       %s;" % surface,
        "  --surface-2:     %s;" % surface_2,
        "  --ink:           %s;" % ink,
        "  --ink-2:         %s;" % mix(ink, plane, 0.26),
        "  --ink-muted:     %s;" % mix(ink, plane, 0.50),
        "  --grid:          %s;" % mix(plane, ink, 0.10),
        "  --axis:          %s;" % mix(plane, ink, 0.24),
        "  --border:        %s;" % tint(ink, 0.12),
        "  --border-strong: %s;" % tint(ink, 0.24),
        "  --shadow:        %s, %s;" % (
            "0 2px 6px " + tint(ink, 0.08), "0 12px 32px " + tint(ink, 0.10)),
    ])
    dark_core = "\n".join([
        "    --plane:         %s;" % d_plane,
        "    --surface:       %s;" % d_surface,
        "    --surface-2:     %s;" % d_surface_2,
        "    --ink:           %s;" % d_ink,
        "    --ink-2:         %s;" % mix(d_ink, d_plane, 0.26),
        "    --ink-muted:     %s;" % mix(d_ink, d_plane, 0.48),
        "    --grid:          %s;" % mix(d_plane, d_ink, 0.11),
        "    --axis:          %s;" % mix(d_plane, d_ink, 0.20),
        "    --border:        %s;" % tint(d_ink, 0.10),
        "    --border-strong: %s;" % tint(d_ink, 0.22),
        "    --shadow:        0 2px 6px rgba(0,0,0,0.40), 0 12px 32px rgba(0,0,0,0.45);",
    ])

    dark_body = "\n".join([
        dark_core, "",
        series_block(d_cs, d_inks, "    "), "",
        dark_semantic,
    ])

    type_block = "\n".join([
        "  /* type — system stacks only, never a web font */",
        "  --font-display: %s;" % font_stack(args.display_font, "system"),
        "  --font-body:    %s;" % font_stack(args.body_font, "system"),
        "  --font-mono:    %s;" % font_stack(args.mono_font, "mono"),
    ])

    # An application with only one colour scheme gets a report with only one.
    # The theme toggle is then dead weight — leave the button out of the body.
    if args.mode == "dark":
        dedent = lambda block: "\n".join(ln[2:] for ln in block.split("\n"))
        light_core, light_semantic = dedent(dark_core), dedent(dark_semantic)
        cs, inks = d_cs, d_inks
        scheme, dark_blocks = "dark", ""
    elif args.mode == "light":
        scheme, dark_blocks = "light", ""
    else:
        scheme = "light"
        dark_blocks = """
@media (prefers-color-scheme: dark) {
  :root:where(:not([data-theme="light"])) {
    color-scheme: dark;
%s
  }
}
:root[data-theme="dark"] {
  color-scheme: dark;
%s
}
""" % (dark_body, dark_body)

    return """/* ==========================================================================
   theme.css — project tokens. THE ONLY FILE THAT CHANGES PER PROJECT.
   Generated by derive_theme.py from the host application's palette.
   Seed: primary %s
   Safe to hand-edit. Regenerate only if the application's palette changes.
   ========================================================================== */
:root {
  color-scheme: %s;

%s

%s

%s

%s

  /* rhythm */
  --wrap:      1040px;
  --measure:   70ch;
  --radius:    6px;
  --radius-sm: 4px;
  --tracking-caps: .12em;
}
%s""" % (primary, scheme, light_core, series_block(cs, inks), light_semantic, type_block, dark_blocks)


def check(args):
    pinned = [c.strip() for c in args.series.split(",")] if args.series else [args.primary]
    plane = args.plane or DEFAULTS["plane"]
    cs = series(args.primary, pinned, plane=plane)
    print("series        bar text   ratio   vs plane", file=sys.stderr)
    ok = True
    for i, c in enumerate(cs):
        col, ratio = best_ink(c)
        vs = contrast(c, plane)
        flag = "" if ratio >= 4.5 else "  << bar text below 4.5:1"
        if ratio < 4.5:
            ok = False
        print("--c%d %s  %s  %5.2f  %5.2f%s" % (i, c, col, ratio, vs, flag), file=sys.stderr)
    print("\nAll series colours pass bar-text contrast." if ok else
          "\nAt least one series colour is hard to label. Adjust its lightness in theme.css.",
          file=sys.stderr)


def main():
    ap = argparse.ArgumentParser(description="Derive report theme tokens from an app palette.")
    ap.add_argument("--primary", required=True, help="the app's main brand colour")
    ap.add_argument("--plane", help="page background")
    ap.add_argument("--surface", help="card background")
    ap.add_argument("--surface-2", dest="surface_2", help="inset background")
    ap.add_argument("--ink", help="primary text colour")
    ap.add_argument("--warn", help="the app's danger/error colour")
    ap.add_argument("--good", help="the app's success colour")
    ap.add_argument("--series", help="comma-separated categorical colours to pin, in order")
    ap.add_argument("--dark-plane", help="dark page background")
    ap.add_argument("--dark-surface", help="dark card background")
    ap.add_argument("--display-font", dest="display_font",
                    help="heading font: a preset (%s) or a literal CSS stack" % ", ".join(FONTS))
    ap.add_argument("--body-font", dest="body_font", help="body font: preset name or literal CSS stack")
    ap.add_argument("--mono-font", dest="mono_font", help="mono font: preset name or literal CSS stack")
    ap.add_argument("--mode", choices=("both", "light", "dark"), default="both",
                    help="colour schemes to emit. 'dark' or 'light' matches a single-scheme "
                         "application and drops the toggle; default emits both")
    ap.add_argument("--check", action="store_true", help="print a contrast report instead of CSS")
    args = ap.parse_args()
    if args.check:
        check(args)
    else:
        sys.stdout.write(build(args))


if __name__ == "__main__":
    main()
